### ISSUE TITLE
Al momento de trackear haga lock en la información

### ISSUE THREAD

**Issue by Gustavowgc** [procesoseficientes/work-timetracker#14]
![image](https://user-images.githubusercontent.com/64803356/93685994-93bade80-fa70-11ea-9998-359267763348.png)

Al momento de iniciar tracking, que se quede guardado los datos con lo que se está haciendo el tracking y se quede bloqueada la información sin poder editar hasta que se de stop .

**Comment by fabrv** [comment]
Si se da track a una nueva información esto detiene la anterior tarea e inicia una nueva. Ese es el comportamiento esperado. 
Forzar al usuario a detener el tracking para iniciar una nueva tarea es un paso inecesario en el flujo que reduce la usabilidad.

Cierro problema.
