### ISSUE TITLE
mal guardado de tarea.

### ISSUE THREAD

**Issue by Gustavowgc** [procesoseficientes/work-timetracker#20]
trackeó mal una tarea:
![image](https://user-images.githubusercontent.com/64803356/93911481-b0992100-fcbf-11ea-9a86-cbcde650488b.png)

nisiquiera son las 4pm y dice que lo detuve a las 4pm, esta tarea fue como de 1 hora si se pudiera correjir.

**Comment by fabrv** [comment]
El problema es que la hora la está guardando en UTC cuando debería de ser en UTC -6, pero la suma debería de estar bien. Arreglo urgente.
