### ISSUE TITLE
Show tracking status (tracking, not tracking)

### ISSUE THREAD

**Issue by Gustavowgc** [procesoseficientes/work-timetracker#22]
que aparezca un punto verde alapar de la palabra tracking cuando se está trackeando.
Si no se está trackeando que desaparezca o se coloque gris.
![image](https://user-images.githubusercontent.com/64803356/94073389-a4db5680-fdb4-11ea-9c68-e4e82acea795.png)

**Comment by fabrv** [comment]
![image](https://user-images.githubusercontent.com/35388973/94177621-1370f080-fe57-11ea-9977-d645a5555c30.png)
El estatus del tracking se puede ver en la linea de tiempo, con una barra animada de progreso y el botón rojo.

Cierro tarea porque feature sería redundante, pero abro uno nuevo para crear ese feature en la pestaña de "Team"
#24
